// Code generated by canoto. DO NOT EDIT.
// versions:
// 	canoto v0.17.3
// source: stub.go

package hookstest

import (
	"io"
	"reflect"
	"sync/atomic"

	"github.com/StephenButtolph/canoto"
)

// Ensure that the generated code is compatible with the library version.
const (
	_ uint = canoto.VersionCompatibility - 0
	_ uint = 0 - canoto.VersionCompatibility
)

// Ensure that unused imports do not error
var (
	_ atomic.Uint64

	_ = io.ErrUnexpectedEOF
)

const (
	canoto__extra__nanoseconds = 1
	canoto__extra__ops         = 2

	canoto__extra__nanoseconds__tag = "\x08" // canoto.Tag(canoto__extra__nanoseconds, canoto.Varint)
	canoto__extra__ops__tag         = "\x12" // canoto.Tag(canoto__extra__ops, canoto.Len)
)

type canotoData_extra struct {
	size uint64
}

// CanotoSpec returns the specification of this canoto message.
func (*extra) CanotoSpec(types ...reflect.Type) *canoto.Spec {
	types = append(types, reflect.TypeOf(extra{}))
	var zero extra
	s := &canoto.Spec{
		Name: "extra",
		Fields: []canoto.FieldType{
			{
				FieldNumber: canoto__extra__nanoseconds,
				Name:        "nanoseconds",
				OneOf:       "",
				TypeInt:     canoto.SizeOf(zero.nanoseconds),
			},
			canoto.FieldTypeFromField(
				/*type inference:*/ (canoto.MakeEntryNilPointer(zero.ops)),
				/*FieldNumber:   */ canoto__extra__ops,
				/*Name:          */ "ops",
				/*FixedLength:   */ 0,
				/*Repeated:      */ true,
				/*OneOf:         */ "",
				/*types:         */ types,
			),
		},
	}
	s.CalculateCanotoCache()
	return s
}

// MakeCanoto creates a new empty value.
func (*extra) MakeCanoto() *extra {
	return new(extra)
}

// UnmarshalCanoto unmarshals a Canoto-encoded byte slice into the struct.
//
// During parsing, the canoto cache is saved.
func (c *extra) UnmarshalCanoto(bytes []byte) error {
	r := canoto.Reader{
		B: bytes,
	}
	return c.UnmarshalCanotoFrom(r)
}

// UnmarshalCanotoFrom populates the struct from a [canoto.Reader]. Most users
// should just use UnmarshalCanoto.
//
// During parsing, the canoto cache is saved.
//
// This function enables configuration of reader options.
func (c *extra) UnmarshalCanotoFrom(r canoto.Reader) error {
	// Zero the struct before unmarshaling.
	*c = extra{}
	atomic.StoreUint64(&c.canotoData.size, uint64(len(r.B)))

	var minField uint32
	for canoto.HasNext(&r) {
		field, wireType, err := canoto.ReadTag(&r)
		if err != nil {
			return err
		}
		if field < minField {
			return canoto.ErrInvalidFieldOrder
		}

		switch field {
		case canoto__extra__nanoseconds:
			if wireType != canoto.Varint {
				return canoto.ErrUnexpectedWireType
			}

			if err := canoto.ReadInt(&r, &c.nanoseconds); err != nil {
				return err
			}
			if canoto.IsZero(c.nanoseconds) {
				return canoto.ErrZeroValue
			}
		case canoto__extra__ops:
			if wireType != canoto.Len {
				return canoto.ErrUnexpectedWireType
			}

			// Read the first entry manually because the tag is already
			// stripped.
			originalUnsafe := r.Unsafe
			r.Unsafe = true
			var msgBytes []byte
			if err := canoto.ReadBytes(&r, &msgBytes); err != nil {
				return err
			}
			r.Unsafe = originalUnsafe

			// Count the number of additional entries after the first entry.
			countMinus1, err := canoto.CountBytes(r.B, canoto__extra__ops__tag)
			if err != nil {
				return err
			}

			c.ops = canoto.MakeSlice(c.ops, countMinus1+1)
			field := c.ops
			additionalField := field[1:]
			if len(msgBytes) != 0 {
				remainingBytes := r.B
				r.B = msgBytes
				if err := (&field[0]).UnmarshalCanotoFrom(r); err != nil {
					return err
				}
				r.B = remainingBytes
			}

			// Read the rest of the entries, stripping the tag each time.
			for i := range additionalField {
				r.B = r.B[len(canoto__extra__ops__tag):]
				r.Unsafe = true
				if err := canoto.ReadBytes(&r, &msgBytes); err != nil {
					return err
				}
				if len(msgBytes) == 0 {
					continue
				}
				r.Unsafe = originalUnsafe

				remainingBytes := r.B
				r.B = msgBytes
				if err := (&additionalField[i]).UnmarshalCanotoFrom(r); err != nil {
					return err
				}
				r.B = remainingBytes
			}
		default:
			return canoto.ErrUnknownField
		}

		minField = field + 1
	}
	return nil
}

// ValidCanoto validates that the struct can be correctly marshaled into the
// Canoto format.
//
// Specifically, ValidCanoto ensures:
// 1. All OneOfs are specified at most once.
// 2. All strings are valid utf-8.
// 3. All custom fields are ValidCanoto.
func (c *extra) ValidCanoto() bool {
	if c == nil {
		return true
	}
	{
		field := c.ops
		for i := range field {
			if !(&field[i]).ValidCanoto() {
				return false
			}
		}
	}
	return true
}

// CalculateCanotoCache populates size and OneOf caches based on the current
// values in the struct.
//
// It is not safe to copy this struct concurrently.
func (c *extra) CalculateCanotoCache() {
	if c == nil {
		return
	}
	var size uint64
	if !canoto.IsZero(c.nanoseconds) {
		size += uint64(len(canoto__extra__nanoseconds__tag)) + canoto.SizeInt(c.nanoseconds)
	}
	{
		field := c.ops
		for i := range field {
			(&field[i]).CalculateCanotoCache()
			fieldSize := (&field[i]).CachedCanotoSize()
			size += uint64(len(canoto__extra__ops__tag)) + canoto.SizeUint(fieldSize) + fieldSize
		}
	}
	atomic.StoreUint64(&c.canotoData.size, size)
}

// CachedCanotoSize returns the previously calculated size of the Canoto
// representation from CalculateCanotoCache.
//
// If CalculateCanotoCache has not yet been called, it will return 0.
//
// If the struct has been modified since the last call to CalculateCanotoCache,
// the returned size may be incorrect.
func (c *extra) CachedCanotoSize() uint64 {
	if c == nil {
		return 0
	}
	return atomic.LoadUint64(&c.canotoData.size)
}

// MarshalCanoto returns the Canoto representation of this struct.
//
// It is assumed that this struct is ValidCanoto.
//
// It is not safe to copy this struct concurrently.
func (c *extra) MarshalCanoto() []byte {
	c.CalculateCanotoCache()
	w := canoto.Writer{
		B: make([]byte, 0, c.CachedCanotoSize()),
	}
	w = c.MarshalCanotoInto(w)
	return w.B
}

// MarshalCanotoInto writes the struct into a [canoto.Writer] and returns the
// resulting [canoto.Writer]. Most users should just use MarshalCanoto.
//
// It is assumed that CalculateCanotoCache has been called since the last
// modification to this struct.
//
// It is assumed that this struct is ValidCanoto.
//
// It is not safe to copy this struct concurrently.
func (c *extra) MarshalCanotoInto(w canoto.Writer) canoto.Writer {
	if c == nil {
		return w
	}
	if !canoto.IsZero(c.nanoseconds) {
		canoto.Append(&w, canoto__extra__nanoseconds__tag)
		canoto.AppendInt(&w, c.nanoseconds)
	}
	{
		field := c.ops
		for i := range field {
			canoto.Append(&w, canoto__extra__ops__tag)
			canoto.AppendUint(&w, (&field[i]).CachedCanotoSize())
			w = (&field[i]).MarshalCanotoInto(w)
		}
	}
	return w
}

const (
	canoto__op__op        = 1
	canoto__op__gas       = 2
	canoto__op__gasFeeCap = 3
	canoto__op__burn      = 4
	canoto__op__mint      = 5

	canoto__op__op__tag        = "\x0a" // canoto.Tag(canoto__op__op, canoto.Len)
	canoto__op__gas__tag       = "\x10" // canoto.Tag(canoto__op__gas, canoto.Varint)
	canoto__op__gasFeeCap__tag = "\x1a" // canoto.Tag(canoto__op__gasFeeCap, canoto.Len)
	canoto__op__burn__tag      = "\x22" // canoto.Tag(canoto__op__burn, canoto.Len)
	canoto__op__mint__tag      = "\x2a" // canoto.Tag(canoto__op__mint, canoto.Len)
)

type canotoData_op struct {
	size          uint64
	gasFeeCapSize uint64
}

// CanotoSpec returns the specification of this canoto message.
func (*Op) CanotoSpec(types ...reflect.Type) *canoto.Spec {
	types = append(types, reflect.TypeOf(Op{}))
	var zero Op
	s := &canoto.Spec{
		Name: "op",
		Fields: []canoto.FieldType{
			{
				FieldNumber:    canoto__op__op,
				Name:           "op",
				OneOf:          "",
				TypeFixedBytes: uint64(len(zero.ID)),
			},
			{
				FieldNumber: canoto__op__gas,
				Name:        "gas",
				OneOf:       "",
				TypeUint:    canoto.SizeOf(zero.Gas),
			},
			{
				FieldNumber: canoto__op__gasFeeCap,
				Name:        "gasFeeCap",
				FixedLength: uint64(len(zero.GasFeeCap)),
				Repeated:    true,
				OneOf:       "",
				TypeUint:    canoto.SizeOf(canoto.MakeEntry(zero.GasFeeCap[:])),
			},
			canoto.FieldTypeFromField(
				/*type inference:*/ (canoto.MakeEntryNilPointer(zero.Burn)),
				/*FieldNumber:   */ canoto__op__burn,
				/*Name:          */ "burn",
				/*FixedLength:   */ 0,
				/*Repeated:      */ true,
				/*OneOf:         */ "",
				/*types:         */ types,
			),
			canoto.FieldTypeFromField(
				/*type inference:*/ (canoto.MakeEntryNilPointer(zero.Mint)),
				/*FieldNumber:   */ canoto__op__mint,
				/*Name:          */ "mint",
				/*FixedLength:   */ 0,
				/*Repeated:      */ true,
				/*OneOf:         */ "",
				/*types:         */ types,
			),
		},
	}
	s.CalculateCanotoCache()
	return s
}

// MakeCanoto creates a new empty value.
func (*Op) MakeCanoto() *Op {
	return new(Op)
}

// UnmarshalCanoto unmarshals a Canoto-encoded byte slice into the struct.
//
// During parsing, the canoto cache is saved.
func (c *Op) UnmarshalCanoto(bytes []byte) error {
	r := canoto.Reader{
		B: bytes,
	}
	return c.UnmarshalCanotoFrom(r)
}

// UnmarshalCanotoFrom populates the struct from a [canoto.Reader]. Most users
// should just use UnmarshalCanoto.
//
// During parsing, the canoto cache is saved.
//
// This function enables configuration of reader options.
func (c *Op) UnmarshalCanotoFrom(r canoto.Reader) error {
	// Zero the struct before unmarshaling.
	*c = Op{}
	atomic.StoreUint64(&c.canotoData.size, uint64(len(r.B)))

	var minField uint32
	for canoto.HasNext(&r) {
		field, wireType, err := canoto.ReadTag(&r)
		if err != nil {
			return err
		}
		if field < minField {
			return canoto.ErrInvalidFieldOrder
		}

		switch field {
		case canoto__op__op:
			if wireType != canoto.Len {
				return canoto.ErrUnexpectedWireType
			}

			const (
				expectedLength       = len(c.ID)
				expectedLengthUint64 = uint64(expectedLength)
			)
			var length uint64
			if err := canoto.ReadUint(&r, &length); err != nil {
				return err
			}
			if length != expectedLengthUint64 {
				return canoto.ErrInvalidLength
			}
			if expectedLength > len(r.B) {
				return io.ErrUnexpectedEOF
			}

			copy((&c.ID)[:], r.B)
			if canoto.IsZero(c.ID) {
				return canoto.ErrZeroValue
			}
			r.B = r.B[expectedLength:]
		case canoto__op__gas:
			if wireType != canoto.Varint {
				return canoto.ErrUnexpectedWireType
			}

			if err := canoto.ReadUint(&r, &c.Gas); err != nil {
				return err
			}
			if canoto.IsZero(c.Gas) {
				return canoto.ErrZeroValue
			}
		case canoto__op__gasFeeCap:
			if wireType != canoto.Len {
				return canoto.ErrUnexpectedWireType
			}

			// Read the packed field bytes.
			originalUnsafe := r.Unsafe
			r.Unsafe = true
			var msgBytes []byte
			if err := canoto.ReadBytes(&r, &msgBytes); err != nil {
				return err
			}
			r.Unsafe = originalUnsafe

			// Read each value from the packed field bytes into the array.
			remainingBytes := r.B
			r.B = msgBytes
			for i := range &c.GasFeeCap {
				if err := canoto.ReadUint(&r, &(&c.GasFeeCap)[i]); err != nil {
					return err
				}
			}
			if canoto.HasNext(&r) {
				return canoto.ErrInvalidLength
			}
			if canoto.IsZero(c.GasFeeCap) {
				return canoto.ErrZeroValue
			}
			r.B = remainingBytes
			atomic.StoreUint64(&c.canotoData.gasFeeCapSize, uint64(len(msgBytes)))
		case canoto__op__burn:
			if wireType != canoto.Len {
				return canoto.ErrUnexpectedWireType
			}

			// Read the first entry manually because the tag is already
			// stripped.
			originalUnsafe := r.Unsafe
			r.Unsafe = true
			var msgBytes []byte
			if err := canoto.ReadBytes(&r, &msgBytes); err != nil {
				return err
			}
			r.Unsafe = originalUnsafe

			// Count the number of additional entries after the first entry.
			countMinus1, err := canoto.CountBytes(r.B, canoto__op__burn__tag)
			if err != nil {
				return err
			}

			c.Burn = canoto.MakeSlice(c.Burn, countMinus1+1)
			field := c.Burn
			additionalField := field[1:]
			if len(msgBytes) != 0 {
				remainingBytes := r.B
				r.B = msgBytes
				if err := (&field[0]).UnmarshalCanotoFrom(r); err != nil {
					return err
				}
				r.B = remainingBytes
			}

			// Read the rest of the entries, stripping the tag each time.
			for i := range additionalField {
				r.B = r.B[len(canoto__op__burn__tag):]
				r.Unsafe = true
				if err := canoto.ReadBytes(&r, &msgBytes); err != nil {
					return err
				}
				if len(msgBytes) == 0 {
					continue
				}
				r.Unsafe = originalUnsafe

				remainingBytes := r.B
				r.B = msgBytes
				if err := (&additionalField[i]).UnmarshalCanotoFrom(r); err != nil {
					return err
				}
				r.B = remainingBytes
			}
		case canoto__op__mint:
			if wireType != canoto.Len {
				return canoto.ErrUnexpectedWireType
			}

			// Read the first entry manually because the tag is already
			// stripped.
			originalUnsafe := r.Unsafe
			r.Unsafe = true
			var msgBytes []byte
			if err := canoto.ReadBytes(&r, &msgBytes); err != nil {
				return err
			}
			r.Unsafe = originalUnsafe

			// Count the number of additional entries after the first entry.
			countMinus1, err := canoto.CountBytes(r.B, canoto__op__mint__tag)
			if err != nil {
				return err
			}

			c.Mint = canoto.MakeSlice(c.Mint, countMinus1+1)
			field := c.Mint
			additionalField := field[1:]
			if len(msgBytes) != 0 {
				remainingBytes := r.B
				r.B = msgBytes
				if err := (&field[0]).UnmarshalCanotoFrom(r); err != nil {
					return err
				}
				r.B = remainingBytes
			}

			// Read the rest of the entries, stripping the tag each time.
			for i := range additionalField {
				r.B = r.B[len(canoto__op__mint__tag):]
				r.Unsafe = true
				if err := canoto.ReadBytes(&r, &msgBytes); err != nil {
					return err
				}
				if len(msgBytes) == 0 {
					continue
				}
				r.Unsafe = originalUnsafe

				remainingBytes := r.B
				r.B = msgBytes
				if err := (&additionalField[i]).UnmarshalCanotoFrom(r); err != nil {
					return err
				}
				r.B = remainingBytes
			}
		default:
			return canoto.ErrUnknownField
		}

		minField = field + 1
	}
	return nil
}

// ValidCanoto validates that the struct can be correctly marshaled into the
// Canoto format.
//
// Specifically, ValidCanoto ensures:
// 1. All OneOfs are specified at most once.
// 2. All strings are valid utf-8.
// 3. All custom fields are ValidCanoto.
func (c *Op) ValidCanoto() bool {
	if c == nil {
		return true
	}
	{
		field := c.Burn
		for i := range field {
			if !(&field[i]).ValidCanoto() {
				return false
			}
		}
	}
	{
		field := c.Mint
		for i := range field {
			if !(&field[i]).ValidCanoto() {
				return false
			}
		}
	}
	return true
}

// CalculateCanotoCache populates size and OneOf caches based on the current
// values in the struct.
//
// It is not safe to copy this struct concurrently.
func (c *Op) CalculateCanotoCache() {
	if c == nil {
		return
	}
	var size uint64
	if !canoto.IsZero(c.ID) {
		size += uint64(len(canoto__op__op__tag)) + canoto.SizeBytes((&c.ID)[:])
	}
	if !canoto.IsZero(c.Gas) {
		size += uint64(len(canoto__op__gas__tag)) + canoto.SizeUint(c.Gas)
	}
	if !canoto.IsZero(c.GasFeeCap) {
		var fieldSize uint64
		for _, v := range &c.GasFeeCap {
			fieldSize += canoto.SizeUint(v)
		}
		size += uint64(len(canoto__op__gasFeeCap__tag)) + canoto.SizeUint(fieldSize) + fieldSize
		atomic.StoreUint64(&c.canotoData.gasFeeCapSize, fieldSize)
	}
	{
		field := c.Burn
		for i := range field {
			(&field[i]).CalculateCanotoCache()
			fieldSize := (&field[i]).CachedCanotoSize()
			size += uint64(len(canoto__op__burn__tag)) + canoto.SizeUint(fieldSize) + fieldSize
		}
	}
	{
		field := c.Mint
		for i := range field {
			(&field[i]).CalculateCanotoCache()
			fieldSize := (&field[i]).CachedCanotoSize()
			size += uint64(len(canoto__op__mint__tag)) + canoto.SizeUint(fieldSize) + fieldSize
		}
	}
	atomic.StoreUint64(&c.canotoData.size, size)
}

// CachedCanotoSize returns the previously calculated size of the Canoto
// representation from CalculateCanotoCache.
//
// If CalculateCanotoCache has not yet been called, it will return 0.
//
// If the struct has been modified since the last call to CalculateCanotoCache,
// the returned size may be incorrect.
func (c *Op) CachedCanotoSize() uint64 {
	if c == nil {
		return 0
	}
	return atomic.LoadUint64(&c.canotoData.size)
}

// MarshalCanoto returns the Canoto representation of this struct.
//
// It is assumed that this struct is ValidCanoto.
//
// It is not safe to copy this struct concurrently.
func (c *Op) MarshalCanoto() []byte {
	c.CalculateCanotoCache()
	w := canoto.Writer{
		B: make([]byte, 0, c.CachedCanotoSize()),
	}
	w = c.MarshalCanotoInto(w)
	return w.B
}

// MarshalCanotoInto writes the struct into a [canoto.Writer] and returns the
// resulting [canoto.Writer]. Most users should just use MarshalCanoto.
//
// It is assumed that CalculateCanotoCache has been called since the last
// modification to this struct.
//
// It is assumed that this struct is ValidCanoto.
//
// It is not safe to copy this struct concurrently.
func (c *Op) MarshalCanotoInto(w canoto.Writer) canoto.Writer {
	if c == nil {
		return w
	}
	if !canoto.IsZero(c.ID) {
		canoto.Append(&w, canoto__op__op__tag)
		canoto.AppendBytes(&w, (&c.ID)[:])
	}
	if !canoto.IsZero(c.Gas) {
		canoto.Append(&w, canoto__op__gas__tag)
		canoto.AppendUint(&w, c.Gas)
	}
	if !canoto.IsZero(c.GasFeeCap) {
		canoto.Append(&w, canoto__op__gasFeeCap__tag)
		canoto.AppendUint(&w, atomic.LoadUint64(&c.canotoData.gasFeeCapSize))
		for _, v := range &c.GasFeeCap {
			canoto.AppendUint(&w, v)
		}
	}
	{
		field := c.Burn
		for i := range field {
			canoto.Append(&w, canoto__op__burn__tag)
			canoto.AppendUint(&w, (&field[i]).CachedCanotoSize())
			w = (&field[i]).MarshalCanotoInto(w)
		}
	}
	{
		field := c.Mint
		for i := range field {
			canoto.Append(&w, canoto__op__mint__tag)
			canoto.AppendUint(&w, (&field[i]).CachedCanotoSize())
			w = (&field[i]).MarshalCanotoInto(w)
		}
	}
	return w
}

const (
	canoto__burn__address = 1
	canoto__burn__nonce   = 2
	canoto__burn__amount  = 3

	canoto__burn__address__tag = "\x0a" // canoto.Tag(canoto__burn__address, canoto.Len)
	canoto__burn__nonce__tag   = "\x10" // canoto.Tag(canoto__burn__nonce, canoto.Varint)
	canoto__burn__amount__tag  = "\x1a" // canoto.Tag(canoto__burn__amount, canoto.Len)
)

type canotoData_burn struct {
	size       uint64
	amountSize uint64
}

// CanotoSpec returns the specification of this canoto message.
func (*AccountDebit) CanotoSpec(...reflect.Type) *canoto.Spec {
	var zero AccountDebit
	s := &canoto.Spec{
		Name: "burn",
		Fields: []canoto.FieldType{
			{
				FieldNumber:    canoto__burn__address,
				Name:           "address",
				OneOf:          "",
				TypeFixedBytes: uint64(len(zero.Address)),
			},
			{
				FieldNumber: canoto__burn__nonce,
				Name:        "nonce",
				OneOf:       "",
				TypeUint:    canoto.SizeOf(zero.Nonce),
			},
			{
				FieldNumber: canoto__burn__amount,
				Name:        "amount",
				FixedLength: uint64(len(zero.Amount)),
				Repeated:    true,
				OneOf:       "",
				TypeUint:    canoto.SizeOf(canoto.MakeEntry(zero.Amount[:])),
			},
		},
	}
	s.CalculateCanotoCache()
	return s
}

// MakeCanoto creates a new empty value.
func (*AccountDebit) MakeCanoto() *AccountDebit {
	return new(AccountDebit)
}

// UnmarshalCanoto unmarshals a Canoto-encoded byte slice into the struct.
//
// During parsing, the canoto cache is saved.
func (c *AccountDebit) UnmarshalCanoto(bytes []byte) error {
	r := canoto.Reader{
		B: bytes,
	}
	return c.UnmarshalCanotoFrom(r)
}

// UnmarshalCanotoFrom populates the struct from a [canoto.Reader]. Most users
// should just use UnmarshalCanoto.
//
// During parsing, the canoto cache is saved.
//
// This function enables configuration of reader options.
func (c *AccountDebit) UnmarshalCanotoFrom(r canoto.Reader) error {
	// Zero the struct before unmarshaling.
	*c = AccountDebit{}
	atomic.StoreUint64(&c.canotoData.size, uint64(len(r.B)))

	var minField uint32
	for canoto.HasNext(&r) {
		field, wireType, err := canoto.ReadTag(&r)
		if err != nil {
			return err
		}
		if field < minField {
			return canoto.ErrInvalidFieldOrder
		}

		switch field {
		case canoto__burn__address:
			if wireType != canoto.Len {
				return canoto.ErrUnexpectedWireType
			}

			const (
				expectedLength       = len(c.Address)
				expectedLengthUint64 = uint64(expectedLength)
			)
			var length uint64
			if err := canoto.ReadUint(&r, &length); err != nil {
				return err
			}
			if length != expectedLengthUint64 {
				return canoto.ErrInvalidLength
			}
			if expectedLength > len(r.B) {
				return io.ErrUnexpectedEOF
			}

			copy((&c.Address)[:], r.B)
			if canoto.IsZero(c.Address) {
				return canoto.ErrZeroValue
			}
			r.B = r.B[expectedLength:]
		case canoto__burn__nonce:
			if wireType != canoto.Varint {
				return canoto.ErrUnexpectedWireType
			}

			if err := canoto.ReadUint(&r, &c.Nonce); err != nil {
				return err
			}
			if canoto.IsZero(c.Nonce) {
				return canoto.ErrZeroValue
			}
		case canoto__burn__amount:
			if wireType != canoto.Len {
				return canoto.ErrUnexpectedWireType
			}

			// Read the packed field bytes.
			originalUnsafe := r.Unsafe
			r.Unsafe = true
			var msgBytes []byte
			if err := canoto.ReadBytes(&r, &msgBytes); err != nil {
				return err
			}
			r.Unsafe = originalUnsafe

			// Read each value from the packed field bytes into the array.
			remainingBytes := r.B
			r.B = msgBytes
			for i := range &c.Amount {
				if err := canoto.ReadUint(&r, &(&c.Amount)[i]); err != nil {
					return err
				}
			}
			if canoto.HasNext(&r) {
				return canoto.ErrInvalidLength
			}
			if canoto.IsZero(c.Amount) {
				return canoto.ErrZeroValue
			}
			r.B = remainingBytes
			atomic.StoreUint64(&c.canotoData.amountSize, uint64(len(msgBytes)))
		default:
			return canoto.ErrUnknownField
		}

		minField = field + 1
	}
	return nil
}

// ValidCanoto validates that the struct can be correctly marshaled into the
// Canoto format.
//
// Specifically, ValidCanoto ensures:
// 1. All OneOfs are specified at most once.
// 2. All strings are valid utf-8.
// 3. All custom fields are ValidCanoto.
func (c *AccountDebit) ValidCanoto() bool {
	if c == nil {
		return true
	}
	return true
}

// CalculateCanotoCache populates size and OneOf caches based on the current
// values in the struct.
//
// It is not safe to copy this struct concurrently.
func (c *AccountDebit) CalculateCanotoCache() {
	if c == nil {
		return
	}
	var size uint64
	if !canoto.IsZero(c.Address) {
		size += uint64(len(canoto__burn__address__tag)) + canoto.SizeBytes((&c.Address)[:])
	}
	if !canoto.IsZero(c.Nonce) {
		size += uint64(len(canoto__burn__nonce__tag)) + canoto.SizeUint(c.Nonce)
	}
	if !canoto.IsZero(c.Amount) {
		var fieldSize uint64
		for _, v := range &c.Amount {
			fieldSize += canoto.SizeUint(v)
		}
		size += uint64(len(canoto__burn__amount__tag)) + canoto.SizeUint(fieldSize) + fieldSize
		atomic.StoreUint64(&c.canotoData.amountSize, fieldSize)
	}
	atomic.StoreUint64(&c.canotoData.size, size)
}

// CachedCanotoSize returns the previously calculated size of the Canoto
// representation from CalculateCanotoCache.
//
// If CalculateCanotoCache has not yet been called, it will return 0.
//
// If the struct has been modified since the last call to CalculateCanotoCache,
// the returned size may be incorrect.
func (c *AccountDebit) CachedCanotoSize() uint64 {
	if c == nil {
		return 0
	}
	return atomic.LoadUint64(&c.canotoData.size)
}

// MarshalCanoto returns the Canoto representation of this struct.
//
// It is assumed that this struct is ValidCanoto.
//
// It is not safe to copy this struct concurrently.
func (c *AccountDebit) MarshalCanoto() []byte {
	c.CalculateCanotoCache()
	w := canoto.Writer{
		B: make([]byte, 0, c.CachedCanotoSize()),
	}
	w = c.MarshalCanotoInto(w)
	return w.B
}

// MarshalCanotoInto writes the struct into a [canoto.Writer] and returns the
// resulting [canoto.Writer]. Most users should just use MarshalCanoto.
//
// It is assumed that CalculateCanotoCache has been called since the last
// modification to this struct.
//
// It is assumed that this struct is ValidCanoto.
//
// It is not safe to copy this struct concurrently.
func (c *AccountDebit) MarshalCanotoInto(w canoto.Writer) canoto.Writer {
	if c == nil {
		return w
	}
	if !canoto.IsZero(c.Address) {
		canoto.Append(&w, canoto__burn__address__tag)
		canoto.AppendBytes(&w, (&c.Address)[:])
	}
	if !canoto.IsZero(c.Nonce) {
		canoto.Append(&w, canoto__burn__nonce__tag)
		canoto.AppendUint(&w, c.Nonce)
	}
	if !canoto.IsZero(c.Amount) {
		canoto.Append(&w, canoto__burn__amount__tag)
		canoto.AppendUint(&w, atomic.LoadUint64(&c.canotoData.amountSize))
		for _, v := range &c.Amount {
			canoto.AppendUint(&w, v)
		}
	}
	return w
}

const (
	canoto__mint__address = 1
	canoto__mint__amount  = 3

	canoto__mint__address__tag = "\x0a" // canoto.Tag(canoto__mint__address, canoto.Len)
	canoto__mint__amount__tag  = "\x1a" // canoto.Tag(canoto__mint__amount, canoto.Len)
)

type canotoData_mint struct {
	size       uint64
	amountSize uint64
}

// CanotoSpec returns the specification of this canoto message.
func (*AccountCredit) CanotoSpec(...reflect.Type) *canoto.Spec {
	var zero AccountCredit
	s := &canoto.Spec{
		Name: "mint",
		Fields: []canoto.FieldType{
			{
				FieldNumber:    canoto__mint__address,
				Name:           "address",
				OneOf:          "",
				TypeFixedBytes: uint64(len(zero.Address)),
			},
			{
				FieldNumber: canoto__mint__amount,
				Name:        "amount",
				FixedLength: uint64(len(zero.Amount)),
				Repeated:    true,
				OneOf:       "",
				TypeUint:    canoto.SizeOf(canoto.MakeEntry(zero.Amount[:])),
			},
		},
	}
	s.CalculateCanotoCache()
	return s
}

// MakeCanoto creates a new empty value.
func (*AccountCredit) MakeCanoto() *AccountCredit {
	return new(AccountCredit)
}

// UnmarshalCanoto unmarshals a Canoto-encoded byte slice into the struct.
//
// During parsing, the canoto cache is saved.
func (c *AccountCredit) UnmarshalCanoto(bytes []byte) error {
	r := canoto.Reader{
		B: bytes,
	}
	return c.UnmarshalCanotoFrom(r)
}

// UnmarshalCanotoFrom populates the struct from a [canoto.Reader]. Most users
// should just use UnmarshalCanoto.
//
// During parsing, the canoto cache is saved.
//
// This function enables configuration of reader options.
func (c *AccountCredit) UnmarshalCanotoFrom(r canoto.Reader) error {
	// Zero the struct before unmarshaling.
	*c = AccountCredit{}
	atomic.StoreUint64(&c.canotoData.size, uint64(len(r.B)))

	var minField uint32
	for canoto.HasNext(&r) {
		field, wireType, err := canoto.ReadTag(&r)
		if err != nil {
			return err
		}
		if field < minField {
			return canoto.ErrInvalidFieldOrder
		}

		switch field {
		case canoto__mint__address:
			if wireType != canoto.Len {
				return canoto.ErrUnexpectedWireType
			}

			const (
				expectedLength       = len(c.Address)
				expectedLengthUint64 = uint64(expectedLength)
			)
			var length uint64
			if err := canoto.ReadUint(&r, &length); err != nil {
				return err
			}
			if length != expectedLengthUint64 {
				return canoto.ErrInvalidLength
			}
			if expectedLength > len(r.B) {
				return io.ErrUnexpectedEOF
			}

			copy((&c.Address)[:], r.B)
			if canoto.IsZero(c.Address) {
				return canoto.ErrZeroValue
			}
			r.B = r.B[expectedLength:]
		case canoto__mint__amount:
			if wireType != canoto.Len {
				return canoto.ErrUnexpectedWireType
			}

			// Read the packed field bytes.
			originalUnsafe := r.Unsafe
			r.Unsafe = true
			var msgBytes []byte
			if err := canoto.ReadBytes(&r, &msgBytes); err != nil {
				return err
			}
			r.Unsafe = originalUnsafe

			// Read each value from the packed field bytes into the array.
			remainingBytes := r.B
			r.B = msgBytes
			for i := range &c.Amount {
				if err := canoto.ReadUint(&r, &(&c.Amount)[i]); err != nil {
					return err
				}
			}
			if canoto.HasNext(&r) {
				return canoto.ErrInvalidLength
			}
			if canoto.IsZero(c.Amount) {
				return canoto.ErrZeroValue
			}
			r.B = remainingBytes
			atomic.StoreUint64(&c.canotoData.amountSize, uint64(len(msgBytes)))
		default:
			return canoto.ErrUnknownField
		}

		minField = field + 1
	}
	return nil
}

// ValidCanoto validates that the struct can be correctly marshaled into the
// Canoto format.
//
// Specifically, ValidCanoto ensures:
// 1. All OneOfs are specified at most once.
// 2. All strings are valid utf-8.
// 3. All custom fields are ValidCanoto.
func (c *AccountCredit) ValidCanoto() bool {
	if c == nil {
		return true
	}
	return true
}

// CalculateCanotoCache populates size and OneOf caches based on the current
// values in the struct.
//
// It is not safe to copy this struct concurrently.
func (c *AccountCredit) CalculateCanotoCache() {
	if c == nil {
		return
	}
	var size uint64
	if !canoto.IsZero(c.Address) {
		size += uint64(len(canoto__mint__address__tag)) + canoto.SizeBytes((&c.Address)[:])
	}
	if !canoto.IsZero(c.Amount) {
		var fieldSize uint64
		for _, v := range &c.Amount {
			fieldSize += canoto.SizeUint(v)
		}
		size += uint64(len(canoto__mint__amount__tag)) + canoto.SizeUint(fieldSize) + fieldSize
		atomic.StoreUint64(&c.canotoData.amountSize, fieldSize)
	}
	atomic.StoreUint64(&c.canotoData.size, size)
}

// CachedCanotoSize returns the previously calculated size of the Canoto
// representation from CalculateCanotoCache.
//
// If CalculateCanotoCache has not yet been called, it will return 0.
//
// If the struct has been modified since the last call to CalculateCanotoCache,
// the returned size may be incorrect.
func (c *AccountCredit) CachedCanotoSize() uint64 {
	if c == nil {
		return 0
	}
	return atomic.LoadUint64(&c.canotoData.size)
}

// MarshalCanoto returns the Canoto representation of this struct.
//
// It is assumed that this struct is ValidCanoto.
//
// It is not safe to copy this struct concurrently.
func (c *AccountCredit) MarshalCanoto() []byte {
	c.CalculateCanotoCache()
	w := canoto.Writer{
		B: make([]byte, 0, c.CachedCanotoSize()),
	}
	w = c.MarshalCanotoInto(w)
	return w.B
}

// MarshalCanotoInto writes the struct into a [canoto.Writer] and returns the
// resulting [canoto.Writer]. Most users should just use MarshalCanoto.
//
// It is assumed that CalculateCanotoCache has been called since the last
// modification to this struct.
//
// It is assumed that this struct is ValidCanoto.
//
// It is not safe to copy this struct concurrently.
func (c *AccountCredit) MarshalCanotoInto(w canoto.Writer) canoto.Writer {
	if c == nil {
		return w
	}
	if !canoto.IsZero(c.Address) {
		canoto.Append(&w, canoto__mint__address__tag)
		canoto.AppendBytes(&w, (&c.Address)[:])
	}
	if !canoto.IsZero(c.Amount) {
		canoto.Append(&w, canoto__mint__amount__tag)
		canoto.AppendUint(&w, atomic.LoadUint64(&c.canotoData.amountSize))
		for _, v := range &c.Amount {
			canoto.AppendUint(&w, v)
		}
	}
	return w
}
