# This file configures github.com/golangci/golangci-lint.

version: "2"

run:
  tests: true

formatters:
  enable:
    - gci
    - gofmt
    - goimports
  settings:
    gci:
      custom-order: true
      sections:
        - standard
        - default
        - prefix(github.com/ava-labs/strevm)
        # The rest of these break developer expections, in increasing order of
        # divergence, so are at the end to increase the chance of being seen.
        - dot
        - blank
  exclusions:
    generated: lax

linters:
  default: none
  enable:
    # Every available linter at the time of writing was considered (quickly) and
    # inclusion was liberal. Linters are good at detecting code smells, but if
    # we find that a particular one causes too many false positives then we can
    # configure it better or, as a last resort, remove it.
    - containedctx
    - errcheck
    - forcetypeassert
    - gocheckcompilerdirectives
    - goheader
    - gomodguard
    - gocritic
    - godoclint
    - gosec
    - govet
    - ineffassign
    - misspell
    - nakedret
    - nestif
    - nilerr
    - nolintlint
    - reassign
    - revive
    - sloglint
    - staticcheck
    - tagliatelle
    - testableexamples
    - testifylint
    - thelper
    - tparallel
    - unconvert
    - unused
    - usestdlibvars
    - whitespace
  settings:
    goheader:
      template-path: .license-header
    gomodguard:
      blocked:
        modules:
          - github.com/ethereum/go-ethereum:
              reason: "Use ava-labs/libevm instead"
          - github.com/ava-labs/avalanchego/graft/coreth:
              reason: "Avoid dependency loop"
          - github.com/ava-labs/avalanchego/graft/evm:
              reason: "Avoid dependency loop"
          - github.com/ava-labs/avalanchego/graft/subnet-evm:
              reason: "Avoid dependency loop"
    staticcheck:
      checks:
        - "all"
        - "-QF1008" # Explicit embedded field selectors improve readability.
    revive:
      rules:
        - name: unused-parameter
          # Method parameters may be required by interfaces and forcing them to be
          # named _ is of questionable benefit.
          disabled: true
        - name: exported
          severity: error
          disabled: false
          exclude: [""]
          arguments:
            - "sayRepetitiveInsteadOfStutters"
        - name: package-comments
          severity: warning
          disabled: false
    testifylint:
      enable-all: true
      disable:
        - require-error # Blanket usage of require over assert is an anti-pattern
  exclusions:
    generated: lax
    presets:
      - std-error-handling # errcheck on Close/Write etc.

