// Code generated by canoto. DO NOT EDIT.
// versions:
// 	canoto v0.17.1
// source: marshal.go

package gastime

import (
	"io"
	"reflect"
	"sync/atomic"

	"github.com/StephenButtolph/canoto"
)

// Ensure that unused imports do not error
var (
	_ atomic.Uint64

	_ = io.ErrUnexpectedEOF
)

const (
	canoto__TimeMarshaler__Time__tag   = "\x0a" // canoto.Tag(1, canoto.Len)
	canoto__TimeMarshaler__target__tag = "\x10" // canoto.Tag(2, canoto.Varint)
	canoto__TimeMarshaler__excess__tag = "\x18" // canoto.Tag(3, canoto.Varint)
)

type canotoData_TimeMarshaler struct {
	size atomic.Uint64
}

// CanotoSpec returns the specification of this canoto message.
func (*TimeMarshaler) CanotoSpec(types ...reflect.Type) *canoto.Spec {
	types = append(types, reflect.TypeOf(TimeMarshaler{}))
	var zero TimeMarshaler
	s := &canoto.Spec{
		Name: "TimeMarshaler",
		Fields: []canoto.FieldType{
			canoto.FieldTypeFromField(
				/*type inference:*/ (zero.Time),
				/*FieldNumber:   */ 1,
				/*Name:          */ "Time",
				/*FixedLength:   */ 0,
				/*Repeated:      */ false,
				/*OneOf:         */ "",
				/*types:         */ types,
			),
			{
				FieldNumber: 2,
				Name:        "target",
				OneOf:       "",
				TypeUint:    canoto.SizeOf(zero.target),
			},
			{
				FieldNumber: 3,
				Name:        "excess",
				OneOf:       "",
				TypeUint:    canoto.SizeOf(zero.excess),
			},
		},
	}
	s.CalculateCanotoCache()
	return s
}

// MakeCanoto creates a new empty value.
func (*TimeMarshaler) MakeCanoto() *TimeMarshaler {
	return new(TimeMarshaler)
}

// UnmarshalCanoto unmarshals a Canoto-encoded byte slice into the struct.
//
// During parsing, the canoto cache is saved.
func (c *TimeMarshaler) UnmarshalCanoto(bytes []byte) error {
	r := canoto.Reader{
		B: bytes,
	}
	return c.UnmarshalCanotoFrom(r)
}

// UnmarshalCanotoFrom populates the struct from a [canoto.Reader]. Most users
// should just use UnmarshalCanoto.
//
// During parsing, the canoto cache is saved.
//
// This function enables configuration of reader options.
func (c *TimeMarshaler) UnmarshalCanotoFrom(r canoto.Reader) error {
	// Zero the struct before unmarshaling.
	*c = TimeMarshaler{}
	c.canotoData.size.Store(uint64(len(r.B)))

	var minField uint32
	for canoto.HasNext(&r) {
		field, wireType, err := canoto.ReadTag(&r)
		if err != nil {
			return err
		}
		if field < minField {
			return canoto.ErrInvalidFieldOrder
		}

		switch field {
		case 1:
			if wireType != canoto.Len {
				return canoto.ErrUnexpectedWireType
			}

			// Read the bytes for the field.
			originalUnsafe := r.Unsafe
			r.Unsafe = true
			var msgBytes []byte
			if err := canoto.ReadBytes(&r, &msgBytes); err != nil {
				return err
			}
			if len(msgBytes) == 0 {
				return canoto.ErrZeroValue
			}
			r.Unsafe = originalUnsafe

			// Unmarshal the field from the bytes.
			remainingBytes := r.B
			r.B = msgBytes
			c.Time = canoto.MakePointer(c.Time)
			if err := (c.Time).UnmarshalCanotoFrom(r); err != nil {
				return err
			}
			r.B = remainingBytes
		case 2:
			if wireType != canoto.Varint {
				return canoto.ErrUnexpectedWireType
			}

			if err := canoto.ReadUint(&r, &c.target); err != nil {
				return err
			}
			if canoto.IsZero(c.target) {
				return canoto.ErrZeroValue
			}
		case 3:
			if wireType != canoto.Varint {
				return canoto.ErrUnexpectedWireType
			}

			if err := canoto.ReadUint(&r, &c.excess); err != nil {
				return err
			}
			if canoto.IsZero(c.excess) {
				return canoto.ErrZeroValue
			}
		default:
			return canoto.ErrUnknownField
		}

		minField = field + 1
	}
	return nil
}

// ValidCanoto validates that the struct can be correctly marshaled into the
// Canoto format.
//
// Specifically, ValidCanoto ensures:
// 1. All OneOfs are specified at most once.
// 2. All strings are valid utf-8.
// 3. All custom fields are ValidCanoto.
func (c *TimeMarshaler) ValidCanoto() bool {
	if c == nil {
		return true
	}
	if c.Time != nil && !(c.Time).ValidCanoto() {
		return false
	}
	return true
}

// CalculateCanotoCache populates size and OneOf caches based on the current
// values in the struct.
func (c *TimeMarshaler) CalculateCanotoCache() {
	if c == nil {
		return
	}
	var size uint64
	if c.Time != nil {
		(c.Time).CalculateCanotoCache()
		if fieldSize := (c.Time).CachedCanotoSize(); fieldSize != 0 {
			size += uint64(len(canoto__TimeMarshaler__Time__tag)) + canoto.SizeUint(fieldSize) + fieldSize
		}
	}
	if !canoto.IsZero(c.target) {
		size += uint64(len(canoto__TimeMarshaler__target__tag)) + canoto.SizeUint(c.target)
	}
	if !canoto.IsZero(c.excess) {
		size += uint64(len(canoto__TimeMarshaler__excess__tag)) + canoto.SizeUint(c.excess)
	}
	c.canotoData.size.Store(size)
}

// CachedCanotoSize returns the previously calculated size of the Canoto
// representation from CalculateCanotoCache.
//
// If CalculateCanotoCache has not yet been called, it will return 0.
//
// If the struct has been modified since the last call to CalculateCanotoCache,
// the returned size may be incorrect.
func (c *TimeMarshaler) CachedCanotoSize() uint64 {
	if c == nil {
		return 0
	}
	return c.canotoData.size.Load()
}

// MarshalCanoto returns the Canoto representation of this struct.
//
// It is assumed that this struct is ValidCanoto.
func (c *TimeMarshaler) MarshalCanoto() []byte {
	c.CalculateCanotoCache()
	w := canoto.Writer{
		B: make([]byte, 0, c.CachedCanotoSize()),
	}
	w = c.MarshalCanotoInto(w)
	return w.B
}

// MarshalCanotoInto writes the struct into a [canoto.Writer] and returns the
// resulting [canoto.Writer]. Most users should just use MarshalCanoto.
//
// It is assumed that CalculateCanotoCache has been called since the last
// modification to this struct.
//
// It is assumed that this struct is ValidCanoto.
func (c *TimeMarshaler) MarshalCanotoInto(w canoto.Writer) canoto.Writer {
	if c == nil {
		return w
	}
	if c.Time != nil {
		if fieldSize := (c.Time).CachedCanotoSize(); fieldSize != 0 {
			canoto.Append(&w, canoto__TimeMarshaler__Time__tag)
			canoto.AppendUint(&w, fieldSize)
			w = (c.Time).MarshalCanotoInto(w)
		}
	}
	if !canoto.IsZero(c.target) {
		canoto.Append(&w, canoto__TimeMarshaler__target__tag)
		canoto.AppendUint(&w, c.target)
	}
	if !canoto.IsZero(c.excess) {
		canoto.Append(&w, canoto__TimeMarshaler__excess__tag)
		canoto.AppendUint(&w, c.excess)
	}
	return w
}
